webtalk_init -webtalk_dir C:/Users/FSociety/Desktop/Vivado_Projects/Projeto_PED_ULA/Projeto_PED_ULA.sim/sim_1/behav/xsim/xsim.dir/decoder_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 15 15:50:24 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "04f86adf-86e7-48d2-83a4-e26f397c3470" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4164c0c20b38425fba25b3de07a975ad" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1700 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5404_KB" -context "xsim\\usage"
webtalk_transmit -clientid 368233186 -regid "" -xml C:/Users/FSociety/Desktop/Vivado_Projects/Projeto_PED_ULA/Projeto_PED_ULA.sim/sim_1/behav/xsim/xsim.dir/decoder_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/FSociety/Desktop/Vivado_Projects/Projeto_PED_ULA/Projeto_PED_ULA.sim/sim_1/behav/xsim/xsim.dir/decoder_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/FSociety/Desktop/Vivado_Projects/Projeto_PED_ULA/Projeto_PED_ULA.sim/sim_1/behav/xsim/xsim.dir/decoder_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
