# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {binary_a[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_a[0]}]
set_property PACKAGE_PIN V16 [get_ports {binary_a[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_a[1]}]
set_property PACKAGE_PIN W16 [get_ports {binary_a[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_a[2]}]
set_property PACKAGE_PIN W17 [get_ports {binary_a[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_a[3]}]
	
set_property PACKAGE_PIN W15 [get_ports {binary_b[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_b[0]}]
set_property PACKAGE_PIN V15 [get_ports {binary_b[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_b[1]}]
set_property PACKAGE_PIN W14 [get_ports {binary_b[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_b[2]}]
set_property PACKAGE_PIN W13 [get_ports {binary_b[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {binary_b[3]}]
	
set_property PACKAGE_PIN V2 [get_ports {modo[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {modo[0]}]
set_property PACKAGE_PIN T3 [get_ports {modo[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {modo[1]}]
set_property PACKAGE_PIN T2 [get_ports {modo[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {modo[2]}]
set_property PACKAGE_PIN R3 [get_ports {modo[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {modo[3]}]
	
set_property PACKAGE_PIN W2 [get_ports {codigo[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {codigo[0]}]
set_property PACKAGE_PIN U1 [get_ports {codigo[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {codigo[1]}]
	
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {segmento_display[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segmento_display[0]}]
set_property PACKAGE_PIN W6 [get_ports {segmento_display[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segmento_display[1]}]
set_property PACKAGE_PIN U8 [get_ports {segmento_display[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segmento_display[2]}]
set_property PACKAGE_PIN V8 [get_ports {segmento_display[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segmento_display[3]}]
set_property PACKAGE_PIN U5 [get_ports {segmento_display[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segmento_display[4]}]
set_property PACKAGE_PIN V5 [get_ports {segmento_display[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segmento_display[5]}]
set_property PACKAGE_PIN U7 [get_ports {segmento_display[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {segmento_display[6]}]

#set_property PACKAGE_PIN V7 [get_ports dp]							
	#set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {anodo_display[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodo_display[0]}]
set_property PACKAGE_PIN U4 [get_ports {anodo_display[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodo_display[1]}]
set_property PACKAGE_PIN V4 [get_ports {anodo_display[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodo_display[2]}]
set_property PACKAGE_PIN W4 [get_ports {anodo_display[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {anodo_display[3]}]